### PR TITLE
Create ThreadRequest

### PR DESCRIPTION
**Pull request by SzkolaWEB**
As the title says. Also, it's my first time with forking someone's project, so don't judge me :p

### CODE REVIEW

**Comment by HappyZombies** [comment]
Few changes! I updated the ThreadController to make it a bit cleaner before you forked it, so I adjusted the controller so that it can use the ThreadRequest. 

Also, authorize() needs to return true. https://laracasts.com/discuss/channels/general-discussion/form-validation-output-forbidden-problem

Oh and we must also include in our threadrequest in our controller!

I also created a CommentRequest since the rules are a little different. I wonder if there is a way to do this differently ?Mhmm. Anyhow. 

Other than that sweet! I shall merge :) ...once I figure this out lol

**Comment by HappyZombies** [comment]
I'm not sure if I did it write.. but here is the commit 

9f6ca60cb54b521c113e1d35f2369e9087b995bb

**Comment by SzkolaWEB** [comment]
My bad. First, I should have introduced myself to your project. Also I need watch closely what I did, so I don't push crappy shit like with the authorization part. I've done this so many times, yet I fail. No crappy PRs, I promise ;)

**Comment by HappyZombies** [comment]
Oh no don't feel bad ! Just a few changes, plus my git skills are still need improvements so we are all learning here !

**Comment by SzkolaWEB** [comment]
Yeah, so lets learn :) I already have some things in my head.

**Pull request closed without merging**
